name: Build

on:
  push:
    branches: [ "testo" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"
    
    - name: Get latest commit hash
      id: latest_commit
      run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build APK
      run: |
        bash build.sh release

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: TrebleApp
        path: TrebleApp.apk
